name: Publish Python distributions to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Only version tags
  workflow_dispatch:

jobs:
  build_linux_x86_64:
    name: Build Linux wheels (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: python -m pip install --upgrade cibuildwheel

      - name: Build Linux wheels
        run: |
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BEFORE_ALL: "pip install numpy"
          CIBW_SKIP: "pp* cp3?-manylinux_i686 *win32 *i386"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
          CIBW_BUILD_VERBOSITY: "1"

      - name: Upload Linux wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-x86_64
          path: wheelhouse

  build_linux_aarch64:
    name: Build Linux wheels (aarch64)
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: python -m pip install --upgrade cibuildwheel

      - name: Build Linux wheels
        run: |
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_LINUX: aarch64
          CIBW_BEFORE_ALL: "pip install numpy"
          CIBW_SKIP: "pp* cp3?-manylinux_i686 *win32 *i386"
          CIBW_BUILD_VERBOSITY: "1"

      - name: Upload Linux wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-aarch64
          path: wheelhouse

  build_windows:
    name: Build Windows wheels
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: python -m pip install --upgrade cibuildwheel

      - name: Build Windows wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "*-arm64"

      - name: Upload Windows wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows
          path: wheelhouse

  build_macos:
    name: Build macOS wheels
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: python -m pip install --upgrade cibuildwheel

      - name: Build macOS wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_MACOS: "x86_64 arm64"

      - name: Upload macOS wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos
          path: wheelhouse

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build sdist
        run: python -m build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist

  publish:
    name: Publish to PyPI
    needs: [build_linux_x86_64, build_linux_aarch64, build_windows, build_macos, build_sdist]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: pypi
      url: https://pypi.org/project/koba
    permissions:
      id-token: write

    steps:
      - name: Download Linux wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-linux-*
          path: dist/
          merge-multiple: true

      - name: Download Windows wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows
          path: dist/

      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos
          path: dist/

      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          token: ${{ secrets.PYPI_API_TOKEN }}
